package com.atlassian.maven.plugins.jgitflow.helper;

public enum ProjectCacheKey
{
    RELEASE_START_LABEL,MASTER_BRANCH,FEATURE_DEPLOY_LABEL,FEATURE_START_LABEL,FEATURE_FINISH_LABEL,HOTFIX_LABEL,HOTFIX_BRANCH,DEVELOP_BRANCH,RELEASE_BRANCH,RELEASE_FINISH_LABEL
}
